# Generated by Django 5.0.6 on 2024-06-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_color_people_color_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='color_name',
            new_name='color',
        ),
    ]
